### ISSUE TITLE
howdo I addsupport for this in amod

### ISSUE THREAD

**Issue by inikishev** [Jamesthe1/GitUpdater#2]
howdo I addsupport for this in amod

**Comment by Jamesthe1** [comment]
1. Create a git repo at the root of your mod
2. Create a github repo (it must be empty, but if it isn't then step 3a will resolve that)
3. Set the origin and push to it with `git push --set-upstream origin <branch>`
    a. If the github repository *is not* empty, you will have to use the `--allow-unrelated-histories` flag.

The mod will now take care of all the pulling, should you be pushing to the github. Note that if you originally cloned from said github repo, the origin is already set.

**Comment by inikishev** [comment]
> 1. Create a git repo at the root of your mod
> 2. Create a github repo (it must be empty, but if it isn't then step 3a will resolve that)
> 3. Set the origin and push to it with `git push --set-upstream origin <branch>`
>    a. If the github repository _is not_ empty, you will have to use the `--allow-unrelated-histories` flag.
> 
> The mod will now take care of all the pulling, should you be pushing to the github. Note that if you originally cloned from said github repo, the origin is already set.

damn
